### ISSUE TITLE
Icon ersetzen

### ISSUE THREAD

**Issue by hagenstrahl** [immergutrocken/website-2021#14]
Brands durch Font Awesome

https://react-icons.github.io/react-icons

@skruvv was hältst Du davon, auch die anderen Icons zu ersetzen?

**Comment by skruvv** [comment]
äh, keine ahnung. seh da nicht durch

**Comment by hagenstrahl** [comment]
Dann vertagen wir das erstmal. Ich glaube, dass da ein bisschen Austausch notwendig für ist :)

**Comment by hagenstrahl** [comment]
Machen wir ein anderes mal
