### ISSUE TITLE
Es werden nicht alle Künstler generiert

### ISSUE THREAD

**Issue by hagenstrahl** [immergutrocken/website-2021#94]
Aktuell werden nur Künstler-Seiten generiert, die in der Sortierung sind. Da aber einige Künstler nicht in der Line-Up Liste auftauchen und trotzdem verlinkt werden sollen, müssen alle Künstler-Seiten generiert werden.

AK:

- [ ] Alle Künstler werden generiert

**Comment by hagenstrahl** [comment]
@lottechar14 
https://www.immergutrocken.de/artist/sind ist jetzt zum Beispiel verfügbar, taucht aber nicht in der Line-Up Liste auf.
Passt das soweit?

**Comment by lottechar14** [comment]
@hagenstrahl 
Genau, so hatten wir uns das vorgestellt.) Nur die Verlinkung im Artikel "Programm" funktioniert noch nicht.

**Comment by hagenstrahl** [comment]
@lottechar14 Ok ich schaue nochmal, das scheint aber ein anderer Fehler zu sein

**Comment by hagenstrahl** [comment]
@lottechar14 Ich habe gerade nochmal deployed, jetzt sind es Links. Die Änderung des Artikels wurde offensichtlich nur gepublished.

Dieses Deployment Thema hat sich bald erledigt, wenn #92 gemerged ist. Dann deployen sich die Seiten alle 10 Sekunden selbst neu 😄

**Comment by lottechar14** [comment]
Ach mensch, was war das wohl. Danke dir, jetzt klappt es @hagenstrahl

**Comment by lottechar14** [comment]
Die Künstler*innen tauchen zwar in der Verlinkung im Programmpunkt "Immergut im Kulturquartier" richtig auf und verlinken auf die korrekten Künstler*innenseiten. Leider funktioniert die Verlinkung aber nicht auf der "Immergut im Kulturquartier" (https://www.immergutrocken.de/article/immergut-im-kulturquartier) - Seite, hier wird man bei einem Klick auf die Künstler*innen im Expander-Unterpunkt "Programm" auf die Fehlerseite 404 weitergeleitet. Kannst du da nochmal schauen?
